### PR TITLE
Adapt iOS app to make use of GMT time instead of local time

### PR DESCRIPTION
**Pull request by rtud**
## Why
We need to have consistent time references within the app.

Right now messages containing time references that get assembled server-side and displayed in the app, differ from the time displayed alongside them.

Example for reminder that references an event that happens at 11:00.
```
10:30: Jim has to take his medicine at 8:00 AM.
```

## What
* [ ] a list of places inside the app where the time references need to be changed to GMT time is assembled inside a comment to this issue
* [x] each time reference inside the app's logic is corrected so that we have a consistent display of time throughout

### CODE REVIEW

**Comment by rtud** [comment]
I have adapted the time references within the app to display using UTC:
* Journal widget on the Home Screen
* Journal screen entries
* Activities screen entries

Merging, thank you!

**Comment by iprunache** [comment]
Shouldn't all time references in the app be local time instead of UTC? I think there's a high chance that elders will get confused with UTC.

**Comment by rtud** [comment]
@iprunache: you are correct - at one point this should be the default behaviour for the app.

The main issue here was that for some of the CAMI functionality we process and compose messages that include time references, server-side. This led to some confusing messages like:

Local & Server time referenced for Journal Entries

In the future we'll need to have a coherent means to process this information factoring in the user's time zone, but for now it seemed the quickest way to making things look consistent for the Expo.

Thank you!

**Comment by iprunache** [comment]
Thanks for the explanation! It wasn't clear that it is temporary, just wanted to make sure :)

**Pull request merged**
