### PR TITLE
Create Tastypie model resource for accessing the Heart Rate information

### PR DESCRIPTION
**Pull request by cretualexandru**
## Why
As a Caregiver using the CAMI system to take care of an Elder, having updated information on his heart rate and step count, helps me understand if his current condition is in order, or if there are any problems regarding his overall health or lack of exercise. This in turn will help CAMI and myself to take action in time.

After defining the model for storing the Heart Rate info in #97, the next thing we have to do is teach the CAMI Cloud how to extract and add data to it.

## What
* [x] a new API endpoint is created for accessing the Heart Rate information
* [x] operating on the new endpoint is tested and works accordingly

### CODE REVIEW

**Comment by cretualexandru** [comment]
This pull request solved the #97 issue also.

**Comment by cretualexandru** [comment]
The HeartRateMeasurementModel does not differ too much from the WeightMeasurementModel, no magic was made there.

The HeartRateMeasurementModelResource is also very similar to WeightMeasurementModel, aside from the status mechanic:
- The status of each value in part will be "ok" if the value is in the [60, 100] interval, or warning otherwise.
- The overall status will be "ok" if the mean value of the last measurements stands in the [60, 100] interval, or warning otherwise.

**Comment by cretualexandru** [comment]
@rtud @aismail ^^ Please take a look and let me know if I can merge. Thank you!

**Comment by cretualexandru** [comment]
I actually discoverd I should add some more status mechanic, not ready for closing!

**Comment by paraschivionut** [comment]
@cretualexandru looks good to me

**Pull request merged**
